StartupEvents.registry('fluid', event => {
    event.create('molten_steel')
        .displayName('Molten Steel')
        .stillTexture('kubejs:fluid/molten_steel_still')
        .flowingTexture('kubejs:fluid/molten_steel_flow')
    event.create('molten_platinum')
        .displayName('Molten Platinum')
        .stillTexture('kubejs:fluid/molten_platinum_still')
        .flowingTexture('kubejs:fluid/molten_platinum_flow')
    event.create('molten_thorium')
        .displayName('Molten Thorium')
        .stillTexture('kubejs:fluid/molten_thorium_still')
        .flowingTexture('kubejs:fluid/molten_thorium_flow')
    event.create('molten_lead')
        .displayName('Molten Lead')
        .stillTexture('kubejs:fluid/molten_lead_still')
        .flowingTexture('kubejs:fluid/molten_lead_flow')
    event.create('molten_nickel')
        .displayName('Molten Nickel')
        .stillTexture('kubejs:fluid/molten_nickel_still')
        .flowingTexture('kubejs:fluid/molten_nickel_flow')
    event.create('molten_tin')
        .displayName('Molten Tin')
        .stillTexture('kubejs:fluid/molten_tin_still')
        .flowingTexture('kubejs:fluid/molten_tin_flow')
    event.create('molten_silver')
        .displayName('Molten Silver')
        .stillTexture('kubejs:fluid/molten_silver_still')
        .flowingTexture('kubejs:fluid/molten_silver_flow')
});
