StartupEvents.registry('fluid', event => {
    event.create('molten_steel')
        .displayName('Molten Steel')
        .stillTexture('kubejs:fluid/molten_steel_still')
        .flowingTexture('kubejs:fluid/molten_steel_flow')
    event.create('molten_platinium')
        .displayName('Molten Platinium')
        .stillTexture('kubejs:fluid/molten_platinium_still')
        .flowingTexture('kubejs:fluid/molten_platinium_flow')
    event.create('molten_thorium')
        .displayName('Molten Thorium')
        .stillTexture('kubejs:fluid/molten_thorium_still')
        .flowingTexture('kubejs:fluid/molten_thorium_flow')
    event.create('molten_lead')
        .displayName('Molten Lead')
        .stillTexture('kubejs:fluid/molten_lead_still')
        .flowingTexture('kubejs:fluid/molten_lead_flow')
});