ClientEvents.lang('en_us', event => {
   event.renameItem('create:filter', 'Applyable list filter');
   event.renameItem('create:attribute_filter', 'Applyable Tag Filter');
   event.renameItem('toms_storage:item_filter', 'Inventory List Filter');
   event.renameItem('toms_storage:polymorphic_item_filter', 'Inventory Polymorphic Filter');
   event.renameItem('toms_storage:tag_item_filter', 'Inventory Tag Filter');
   event.renameItem('oritech:item_filter_block', 'Item Pipe Filter');
   event.renameItem('confluence:granite', 'Dark Granite');
   event.renameItem('confluence:granite','Dark Granite Colmun');
   event.renameItem('confluence:granite_bricks','Dark Granite Bricks');
   event.renameItem('confluence:cracked_granite_bricks','Cracked Dark Granite Bricks');
   event.renameItem('confluence:polished_granite','Polished Dark Granite');
   event.renameItem('confluence:chiseled_granite_bricks','Chiseled Dark Granite');
   event.renameItem('confluence:granite_chest','Dark Granite Chest');
   event.renameItem('confluence:granite_tapered_block','Dark Granite Tapered Block');
   event.renameItem('oritech:fluid_pipe','Silicon Fluid Pipe');
   event.renameItem('oritech:steam_engine_block','Steam Dripper');
   event.renameItem('minecraft:vault','Trial Vault');
   event.renameItem('toms_storage:wireless_terminal','Wireless Inventory Terminal');
   event.renameItem('toms_storage:adv_wireless_terminal', 'Advanced Wireless Inventory Terminal');
   event.renameItem('createcasing:processing_chorium', 'Processing Chromatic Compound')
   event.renameItem('toms_storage:inventory_proxy', 'Inventory Access Chain')
   event.renameItem('create_new_age:nuclear_fuel', 'Thorium Tube')
   event.renameItem('create_new_age:incomplete_fuel', 'Incomplete Tube')
   //event.renameFluid('confluence:honey', "Royal Honey")
   event.renameItem('confluence:honey_bucket', "Royal Honey Bucket")
   event.renameItem('confluence:bottomless_honey_bucket', "Bottomless Royal Honey Bucket")
   event.renameItem('toms_storage:paint_kit', "Paint Kit (STORAGE)")
   event.renameItem('drones:drill', "Drone Drill")
   event.renameItem('oritech:hand_drill', "Electric Drill")
   event.renameItem('drones:frame', 'Drone Assembly Frame')
   event.renameItem('drones:controller', 'Drone Assembly Terminal')
   event.renameItem('drones:ion_thruster', 'Drone Ion Thruster')
   event.renameItem('belts:chute', 'Conveyor Funnel')
   event.renameItem('cyberspace:graphene_coated_iron_ingot', 'Graphene Ingot')
   event.renameItem('cyberspace:graphene', 'Graphene Plate')
   event.renameItem('cyberspace:graphite_blend', 'Graphene Dust')
   event.renameItem('cyberspace:terminal_block', "CyberSpace Terminal")
   event.renameItem('confluence:gold_dust', "Gold Broaddust")
   event.renameItem('confluence:granite_column', "Dark Granite Colmun")
   event.renameItem('confluence:granite', 'Dark Granite')
   event.renameItem('confluence:fertilizer', "Super Fertilizer")

   // BAOBAB
   //  Confluence
   event.renameItem('confluence:baobab_log', "Clair Baobab Log")
   event.renameItem('confluence:baobab_leaves', "Clair Baobab Leaves")
   event.renameItem('confluence:baobab_sapling', "Clair Baobab Sapling")
   event.renameItem('confluence:baobab_planks', "Clair Baobab Planks")
   event.renameItem('confluence:stripped_baobab_log', "Stripped Clair Baobab Log")
   event.renameItem('confluence:baobab_wood', "Clair Baobab Wood")
   event.renameItem('confluence:stripped_baobab_wood', "Stripped Clair Baobab Wood")
   event.renameItem('confluence:baobab_button', "Clair Baobab Button")
   event.renameItem('confluence:baobab_fence', "Clair Baobab Fence")
   event.renameItem('confluence:baobab_fence_gate', "Clair Baobab Fence Gate")
   event.renameItem('confluence:baobab_pressure_plate', "Clair Baobab Pressure Plate")
   event.renameItem('confluence:baobab_slab', "Clair Baobab Slab")
   event.renameItem('confluence:baobab_stairs', "Clair Baobab Stairs")
   event.renameItem('confluence:baobab_sign', "Clair Baobab Sign")
   event.renameItem('confluence:baobab_trapdoor', "Clair Baobab Trapdoor")
   event.renameItem('confluence:baobab_door', "Clair Baobab Door")
   event.renameItem('confluence:baobab_hanging_sign', "Clair Baobab Hanging Sign")
   event.renameItem('confluence:chiseled_baobab_planks', "Chsiled Clair Baobab Planks")
   event.renameItem('confluence:baobab_boat', "Clair Baobab Boat")
   event.renameItem('confluence:baobab_chest_boat', "Clair Baobab Chest Boat")
   //  Regions Unexplored
   event.renameItem('regions_unexplored:baobab_log', "Rose Baobab Log")
   event.renameItem('regions_unexplored:baobab_leaves', "Rose Baobab Leaves")
   event.renameItem('regions_unexplored:baobab_sapling', "Rose Baobab Sapling")
   event.renameItem('regions_unexplored:baobab_shrub', "Rose Baobab Shrub")
   event.renameItem('regions_unexplored:baobab_planks', "Rose Baobab Planks")
   event.renameItem('confluence:stripped_baobab_log', "Stripped Rose Baobab Log")
   event.renameItem('regions_unexplored:baobab_wood', "Rose Baobab Wood")
   event.renameItem('confluence:stripped_baobab_wood', "Stripped Rose Baobab Wood")
   event.renameItem('regions_unexplored:baobab_button', "Rose Baobab Button")
   event.renameItem('regions_unexplored:baobab_fence', "Rose Baobab Fence")
   event.renameItem('regions_unexplored:baobab_fence_gate', "Rose Baobab Fence Gate")
   event.renameItem('regions_unexplored:baobab_pressure_plate', "Rose Baobab Pressure Plate")
   event.renameItem('regions_unexplored:baobab_slab', "Rose Baobab Slab")
   event.renameItem('regions_unexplored:baobab_stairs', "Rose Baobab Stairs")
   event.renameItem('regions_unexplored:baobab_sign', "Rose Baobab Sign")
   event.renameItem('regions_unexplored:baobab_trapdoor', "Rose Baobab Trapdoor")
   event.renameItem('regions_unexplored:baobab_door', "Rose Baobab Door")
   event.renameItem('regions_unexplored:baobab_hanging_sign', "Rose Baobab Hanging Sign")
   event.renameItem('regions_unexplored:baobab_boat', "Rose Baobab Boat")
   event.renameItem('regions_unexplored:baobab_chest_boat', "Rose Baobab Chest Boat")
   //  biomeswevegone
   event.renameItem('biomeswevegone:baobab_log', "Dark Baobab Log")
   event.renameItem('biomeswevegone:baobab_leaves', "Dark Baobab Leaves")
   event.renameItem('biomeswevegone:baobab_sapling', "Dark Baobab Sapling")
   event.renameItem('biomeswevegone:baobab_planks', "Dark Baobab Planks")
   event.renameItem('confluence:stripped_baobab_log', "Stripped Dark Baobab Log")
   event.renameItem('biomeswevegone:baobab_wood', "Dark Baobab Wood")
   event.renameItem('confluence:stripped_baobab_wood', "Stripped Dark Baobab Wood")
   event.renameItem('biomeswevegone:baobab_button', "Dark Baobab Button")
   event.renameItem('biomeswevegone:baobab_fence', "Dark Baobab Fence")
   event.renameItem('biomeswevegone:baobab_fence_gate', "Dark Baobab Fence Gate")
   event.renameItem('biomeswevegone:baobab_pressure_plate', "Dark Baobab Pressure Plate")
   event.renameItem('biomeswevegone:baobab_slab', "Dark Baobab Slab")
   event.renameItem('biomeswevegone:baobab_stairs', "Dark Baobab Stairs")
   event.renameItem('biomeswevegone:baobab_sign', "Dark Baobab Sign")
   event.renameItem('biomeswevegone:baobab_trapdoor', "Dark Baobab Trapdoor")
   event.renameItem('biomeswevegone:baobab_door', "Dark Baobab Door")
   event.renameItem('biomeswevegone:baobab_hanging_sign', "Dark Baobab Hanging Sign")
   event.renameItem('biomeswevegone:ripe_baobab_leaves', "Ripe Dark Baobab Leaves")
   event.renameItem('biomeswevegone:flowering_baobab_leaves', "Flowering Dark Baobab Leaves")
   event.renameItem('biomeswevegone:baobab_boat', "Dark Baobab Boat")
   event.renameItem('biomeswevegone:baobab_chest_boat', "Dark Baobab Chest Boat")

   // PALM
   //  Confluence
   event.renameItem('confluence:palm_log', "Beach Palm Log")
   event.renameItem('confluence:palm_leaves', "Beach Palm Leaves")
   event.renameItem('confluence:palm_sapling', "Beach Palm Sapling")
   event.renameItem('confluence:palm_planks', "Beach Palm Planks")
   event.renameItem('confluence:stripped_palm_log', "Stripped Beach Palm Log")
   event.renameItem('confluence:palm_wood', "Beach Palm Wood")
   event.renameItem('confluence:stripped_palm_wood', "Stripped Beach Palm Wood")
   event.renameItem('confluence:palm_button', "Beach Palm Button")
   event.renameItem('confluence:palm_fence', "Beach Palm Fence")
   event.renameItem('confluence:palm_fence_gate', "Beach Palm Fence Gate")
   event.renameItem('confluence:palm_pressure_plate', "Beach Palm Pressure Plate")
   event.renameItem('confluence:palm_slab', "Beach Palm Slab")
   event.renameItem('confluence:palm_stairs', "Beach Palm Stairs")
   event.renameItem('confluence:palm_sign', "Beach Palm Sign")
   event.renameItem('confluence:palm_trapdoor', "Beach Palm Trapdoor")
   event.renameItem('confluence:palm_door', "Beach Palm Door")
   event.renameItem('confluence:palm_hanging_sign', "Beach Palm Hanging Sign")
   event.renameItem('confluence:chiseled_palm_planks', "Chsiled Beach Palm Planks")
   event.renameItem('confluence:palm_boat', "Beach Palm Boat")
   event.renameItem('confluence:palm_chest_boat', "Beach Palm Chest Boat")
   //  Regions Unexplored
   event.renameItem('regions_unexplored:palm_log', "Clair Palm Log")
   event.renameItem('regions_unexplored:palm_leaves', "Clair Palm Leaves")
   event.renameItem('regions_unexplored:palm_sapling', "Clair Palm Sapling")
   event.renameItem('regions_unexplored:palm_shrub', "Clair Palm Shrub")
   event.renameItem('regions_unexplored:palm_planks', "Clair Palm Planks")
   event.renameItem('confluence:stripped_palm_log', "Stripped Clair Palm Log")
   event.renameItem('regions_unexplored:palm_wood', "Clair Palm Wood")
   event.renameItem('confluence:stripped_palm_wood', "Stripped Clair Palm Wood")
   event.renameItem('regions_unexplored:palm_button', "Clair Palm Button")
   event.renameItem('regions_unexplored:palm_fence', "Clair Palm Fence")
   event.renameItem('regions_unexplored:palm_fence_gate', "Clair Palm Fence Gate")
   event.renameItem('regions_unexplored:palm_pressure_plate', "Clair Palm Pressure Plate")
   event.renameItem('regions_unexplored:palm_slab', "Clair Palm Slab")
   event.renameItem('regions_unexplored:palm_stairs', "Clair Palm Stairs")
   event.renameItem('regions_unexplored:palm_sign', "Clair Palm Sign")
   event.renameItem('regions_unexplored:palm_trapdoor', "Clair Palm Trapdoor")
   event.renameItem('regions_unexplored:palm_door', "Clair Palm Door")
   event.renameItem('regions_unexplored:palm_hanging_sign', "Clair Palm Hanging Sign")
   event.renameItem('regions_unexplored:palm_boat', "Clair Palm Boat")
   event.renameItem('regions_unexplored:palm_chest_boat', "Clair Palm Chest Boat")
   //  biomeswevegone
   event.renameItem('biomeswevegone:palm_log', "Dark Palm Log")
   event.renameItem('biomeswevegone:palm_leaves', "Dark Palm Leaves")
   event.renameItem('biomeswevegone:palm_sapling', "Dark Palm Sapling")
   event.renameItem('biomeswevegone:palm_planks', "Dark Palm Planks")
   event.renameItem('confluence:stripped_palm_log', "Stripped Dark Palm Log")
   event.renameItem('biomeswevegone:palm_wood', "Dark Palm Wood")
   event.renameItem('confluence:stripped_palm_wood', "Stripped Dark Palm Wood")
   event.renameItem('biomeswevegone:palm_button', "Dark Palm Button")
   event.renameItem('biomeswevegone:palm_fence', "Dark Palm Fence")
   event.renameItem('biomeswevegone:palm_fence_gate', "Dark Palm Fence Gate")
   event.renameItem('biomeswevegone:palm_pressure_plate', "Dark Palm Pressure Plate")
   event.renameItem('biomeswevegone:palm_slab', "Dark Palm Slab")
   event.renameItem('biomeswevegone:palm_stairs', "Dark Palm Stairs")
   event.renameItem('biomeswevegone:palm_sign', "Dark Palm Sign")
   event.renameItem('biomeswevegone:palm_trapdoor', "Dark Palm Trapdoor")
   event.renameItem('biomeswevegone:palm_door', "Dark Palm Door")
   event.renameItem('biomeswevegone:palm_hanging_sign', "Dark Palm Hanging Sign")
   event.renameItem('biomeswevegone:ripe_palm_leaves', "Ripe Dark Palm Leaves")
   event.renameItem('biomeswevegone:flowering_palm_leaves', "Flowering Dark Palm Leaves")
   event.renameItem('biomeswevegone:palm_boat', "Dark Palm Boat")
   event.renameItem('biomeswevegone:palm_chest_boat', "Dark Palm Chest Boat")

   // WILLOW
   //  Regions Unexplored
   event.renameItem('regions_unexplored:willow_log', "Pale Willow Log")
   event.renameItem('regions_unexplored:willow_leaves', "Pale Willow Leaves")
   event.renameItem('regions_unexplored:willow_sapling', "Pale Willow Sapling")
   event.renameItem('regions_unexplored:willow_shrub', "Pale Willow Shrub")
   event.renameItem('regions_unexplored:willow_planks', "Pale Willow Planks")
   event.renameItem('confluence:stripped_willow_log', "Stripped Pale Willow Log")
   event.renameItem('regions_unexplored:willow_wood', "Pale Willow Wood")
   event.renameItem('confluence:stripped_willow_wood', "Stripped Pale Willow Wood")
   event.renameItem('regions_unexplored:willow_button', "Pale Willow Button")
   event.renameItem('regions_unexplored:willow_fence', "Pale Willow Fence")
   event.renameItem('regions_unexplored:willow_fence_gate', "Pale Willow Fence Gate")
   event.renameItem('regions_unexplored:willow_pressure_plate', "Pale Willow Pressure Plate")
   event.renameItem('regions_unexplored:willow_slab', "Pale Willow Slab")
   event.renameItem('regions_unexplored:willow_stairs', "Pale Willow Stairs")
   event.renameItem('regions_unexplored:willow_sign', "Pale Willow Sign")
   event.renameItem('regions_unexplored:willow_trapdoor', "Pale Willow Trapdoor")
   event.renameItem('regions_unexplored:willow_door', "Pale Willow Door")
   event.renameItem('regions_unexplored:willow_hanging_sign', "Pale Willow Hanging Sign")
   event.renameItem('regions_unexplored:willow_boat', "Pale Willow Boat")
   event.renameItem('regions_unexplored:willow_chest_boat', "Pale Willow Chest Boat")
   //  biomeswevegone
   event.renameItem('biomeswevegone:willow_log', "Swamp Willow Log")
   event.renameItem('biomeswevegone:willow_leaves', "Swamp Willow Leaves")
   event.renameItem('biomeswevegone:willow_sapling', "Swamp Willow Sapling")
   event.renameItem('biomeswevegone:willow_planks', "Swamp Willow Planks")
   event.renameItem('confluence:stripped_willow_log', "Stripped Swamp Willow Log")
   event.renameItem('biomeswevegone:willow_wood', "Swamp Willow Wood")
   event.renameItem('confluence:stripped_willow_wood', "Stripped Swamp Willow Wood")
   event.renameItem('biomeswevegone:willow_button', "Swamp Willow Button")
   event.renameItem('biomeswevegone:willow_fence', "Swamp Willow Fence")
   event.renameItem('biomeswevegone:willow_fence_gate', "Swamp Willow Fence Gate")
   event.renameItem('biomeswevegone:willow_pressure_plate', "Swamp Willow Pressure Plate")
   event.renameItem('biomeswevegone:willow_slab', "Swamp Willow Slab")
   event.renameItem('biomeswevegone:willow_stairs', "Swamp Willow Stairs")
   event.renameItem('biomeswevegone:willow_sign', "Swamp Willow Sign")
   event.renameItem('biomeswevegone:willow_trapdoor', "Swamp Willow Trapdoor")
   event.renameItem('biomeswevegone:willow_door', "Swamp Willow Door")
   event.renameItem('biomeswevegone:willow_hanging_sign', "Swamp Willow Hanging Sign")
   event.renameItem('biomeswevegone:ripe_willow_leaves', "Ripe Swamp Willow Leaves")
   event.renameItem('biomeswevegone:flowering_willow_leaves', "Flowering Swamp Willow Leaves")
   event.renameItem('biomeswevegone:willow_boat', "Swamp Willow Boat")
   event.renameItem('biomeswevegone:willow_chest_boat', "Swamp Willow Chest Boat")
});