musicType = "confluence_music:confluence"
# Default: 50
# Range: 0 ~ 1200
lastSongFadeOutTime = 100
# Default: 2400
# Range: 10 ~ 18000
nextSongDelay = 2400
keepCreativeModeMusic = true
denyVanillaMusic = false
